// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvgqigqbagfefyjwhznj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2Z3FpZ3FiYWdmZWZ5andoem5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1Mzc4NjQsImV4cCI6MjA2NDExMzg2NH0.HMlqaGjCY0Gv7W_NyixVCvoomN2RhUOyKAzz83kBu3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);